# Generated by Django 2.1.2 on 2018-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
